/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AllExercisesResponse18 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5146735623508221509L;
    private String name;
    private String caloryCount;
    private String category;
    private String cardioSubcategory;
    private String primaryMuscleGroup;
    private String exerciseId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
        notifyObservers(this.name);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("calory_count")
    public String getCaloryCount ( ) { 
        return this.caloryCount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("calory_count")
    public void setCaloryCount (String value) { 
        this.caloryCount = value;
        notifyObservers(this.caloryCount);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("category")
    public String getCategory ( ) { 
        return this.category;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("category")
    public void setCategory (String value) { 
        this.category = value;
        notifyObservers(this.category);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cardio_subcategory")
    public String getCardioSubcategory ( ) { 
        return this.cardioSubcategory;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cardio_subcategory")
    public void setCardioSubcategory (String value) { 
        this.cardioSubcategory = value;
        notifyObservers(this.cardioSubcategory);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("primary_muscle_group")
    public String getPrimaryMuscleGroup ( ) { 
        return this.primaryMuscleGroup;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("primary_muscle_group")
    public void setPrimaryMuscleGroup (String value) { 
        this.primaryMuscleGroup = value;
        notifyObservers(this.primaryMuscleGroup);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exercise_id")
    public String getExerciseId ( ) { 
        return this.exerciseId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exercise_id")
    public void setExerciseId (String value) { 
        this.exerciseId = value;
        notifyObservers(this.exerciseId);
    }
 
}
 