/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AllFoodBrandsResponse 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5091281808543049847L;
    private String brandName;
    private String foodBrandId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("brand_name")
    public String getBrandName ( ) { 
        return this.brandName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("brand_name")
    public void setBrandName (String value) { 
        this.brandName = value;
        notifyObservers(this.brandName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("food_brand_id")
    public String getFoodBrandId ( ) { 
        return this.foodBrandId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("food_brand_id")
    public void setFoodBrandId (String value) { 
        this.foodBrandId = value;
        notifyObservers(this.foodBrandId);
    }
 
}
 