/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AllGenericsResponse 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5188645011943928026L;
    private String name;
    private String pregnancyCategory;
    private String lactationCategory;
    private String instructions;
    private String faqs;
    private int genricId;
    private String sideEffects;
    private String howItWorks;
    private String therapeuticClass;
    private String usedFor;
    private String strength;
    private String schedule;
    private String alcoholInteractionDescription;
    private boolean alcoholNteraction;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
        notifyObservers(this.name);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("pregnancy_category")
    public String getPregnancyCategory ( ) { 
        return this.pregnancyCategory;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("pregnancy_category")
    public void setPregnancyCategory (String value) { 
        this.pregnancyCategory = value;
        notifyObservers(this.pregnancyCategory);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lactation_category")
    public String getLactationCategory ( ) { 
        return this.lactationCategory;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lactation_category")
    public void setLactationCategory (String value) { 
        this.lactationCategory = value;
        notifyObservers(this.lactationCategory);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("instructions")
    public String getInstructions ( ) { 
        return this.instructions;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("instructions")
    public void setInstructions (String value) { 
        this.instructions = value;
        notifyObservers(this.instructions);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("faqs")
    public String getFaqs ( ) { 
        return this.faqs;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("faqs")
    public void setFaqs (String value) { 
        this.faqs = value;
        notifyObservers(this.faqs);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("genric_id")
    public int getGenricId ( ) { 
        return this.genricId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("genric_id")
    public void setGenricId (int value) { 
        this.genricId = value;
        notifyObservers(this.genricId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("side_effects")
    public String getSideEffects ( ) { 
        return this.sideEffects;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("side_effects")
    public void setSideEffects (String value) { 
        this.sideEffects = value;
        notifyObservers(this.sideEffects);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("how_it_works")
    public String getHowItWorks ( ) { 
        return this.howItWorks;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("how_it_works")
    public void setHowItWorks (String value) { 
        this.howItWorks = value;
        notifyObservers(this.howItWorks);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("therapeutic_class")
    public String getTherapeuticClass ( ) { 
        return this.therapeuticClass;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("therapeutic_class")
    public void setTherapeuticClass (String value) { 
        this.therapeuticClass = value;
        notifyObservers(this.therapeuticClass);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("used_for")
    public String getUsedFor ( ) { 
        return this.usedFor;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("used_for")
    public void setUsedFor (String value) { 
        this.usedFor = value;
        notifyObservers(this.usedFor);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("strength")
    public String getStrength ( ) { 
        return this.strength;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("strength")
    public void setStrength (String value) { 
        this.strength = value;
        notifyObservers(this.strength);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("schedule")
    public String getSchedule ( ) { 
        return this.schedule;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("schedule")
    public void setSchedule (String value) { 
        this.schedule = value;
        notifyObservers(this.schedule);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("alcohol_interaction_description")
    public String getAlcoholInteractionDescription ( ) { 
        return this.alcoholInteractionDescription;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("alcohol_interaction_description")
    public void setAlcoholInteractionDescription (String value) { 
        this.alcoholInteractionDescription = value;
        notifyObservers(this.alcoholInteractionDescription);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("alcohol_nteraction")
    public boolean getAlcoholNteraction ( ) { 
        return this.alcoholNteraction;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("alcohol_nteraction")
    public void setAlcoholNteraction (boolean value) { 
        this.alcoholNteraction = value;
        notifyObservers(this.alcoholNteraction);
    }
 
}
 