/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Constituent 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4770097812057315013L;
    private String name;
    private String strength;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
        notifyObservers(this.name);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("strength")
    public String getStrength ( ) { 
        return this.strength;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("strength")
    public void setStrength (String value) { 
        this.strength = value;
        notifyObservers(this.strength);
    }
 
}
 