/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GenericsResponse 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5074666464905818265L;
    private String name;
    private String genericId;
    private List<String> theraupticUses;
    private double searchScore;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
        notifyObservers(this.name);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("generic_id")
    public String getGenericId ( ) { 
        return this.genericId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("generic_id")
    public void setGenericId (String value) { 
        this.genericId = value;
        notifyObservers(this.genericId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("therauptic_uses")
    public List<String> getTheraupticUses ( ) { 
        return this.theraupticUses;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("therauptic_uses")
    public void setTheraupticUses (List<String> value) { 
        this.theraupticUses = value;
        notifyObservers(this.theraupticUses);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("search_score")
    public double getSearchScore ( ) { 
        return this.searchScore;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("search_score")
    public void setSearchScore (double value) { 
        this.searchScore = value;
        notifyObservers(this.searchScore);
    }
 
}
 