/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Interaction 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5217234937683314216L;
    private List<Item> items;
    private String severity;
    private String description;
    private String source;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("items")
    public List<Item> getItems ( ) { 
        return this.items;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("items")
    public void setItems (List<Item> value) { 
        this.items = value;
        notifyObservers(this.items);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("severity")
    public String getSeverity ( ) { 
        return this.severity;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("severity")
    public void setSeverity (String value) { 
        this.severity = value;
        notifyObservers(this.severity);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
        notifyObservers(this.description);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("source")
    public String getSource ( ) { 
        return this.source;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("source")
    public void setSource (String value) { 
        this.source = value;
        notifyObservers(this.source);
    }
 
}
 