/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class LabTestData 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5357695570986814923L;
    private String orderingInformation;
    private String alternateNames;
    private String laboratory;
    private String testCode;
    private String specimenTypes;
    private String containerTypes;
    private String minimumAdultVolume;
    private String frequency;
    private String externalLaboratory;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Ordering information")
    public String getOrderingInformation ( ) { 
        return this.orderingInformation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Ordering information")
    public void setOrderingInformation (String value) { 
        this.orderingInformation = value;
        notifyObservers(this.orderingInformation);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Alternate names")
    public String getAlternateNames ( ) { 
        return this.alternateNames;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Alternate names")
    public void setAlternateNames (String value) { 
        this.alternateNames = value;
        notifyObservers(this.alternateNames);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Laboratory")
    public String getLaboratory ( ) { 
        return this.laboratory;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Laboratory")
    public void setLaboratory (String value) { 
        this.laboratory = value;
        notifyObservers(this.laboratory);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Test Code")
    public String getTestCode ( ) { 
        return this.testCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Test Code")
    public void setTestCode (String value) { 
        this.testCode = value;
        notifyObservers(this.testCode);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Specimen types")
    public String getSpecimenTypes ( ) { 
        return this.specimenTypes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Specimen types")
    public void setSpecimenTypes (String value) { 
        this.specimenTypes = value;
        notifyObservers(this.specimenTypes);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Container types")
    public String getContainerTypes ( ) { 
        return this.containerTypes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Container types")
    public void setContainerTypes (String value) { 
        this.containerTypes = value;
        notifyObservers(this.containerTypes);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Minimum Adult Volume")
    public String getMinimumAdultVolume ( ) { 
        return this.minimumAdultVolume;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Minimum Adult Volume")
    public void setMinimumAdultVolume (String value) { 
        this.minimumAdultVolume = value;
        notifyObservers(this.minimumAdultVolume);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Frequency")
    public String getFrequency ( ) { 
        return this.frequency;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Frequency")
    public void setFrequency (String value) { 
        this.frequency = value;
        notifyObservers(this.frequency);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("External Laboratory")
    public String getExternalLaboratory ( ) { 
        return this.externalLaboratory;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("External Laboratory")
    public void setExternalLaboratory (String value) { 
        this.externalLaboratory = value;
        notifyObservers(this.externalLaboratory);
    }
 
}
 