/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class LabTestData34 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5561871502942195257L;
    private String orderingInformation;
    private String laboratory;
    private String testCode;
    private String specimenTypes;
    private String containerTypes;
    private String collectionInstructions;
    private String frequency;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Ordering information")
    public String getOrderingInformation ( ) { 
        return this.orderingInformation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Ordering information")
    public void setOrderingInformation (String value) { 
        this.orderingInformation = value;
        notifyObservers(this.orderingInformation);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Laboratory")
    public String getLaboratory ( ) { 
        return this.laboratory;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Laboratory")
    public void setLaboratory (String value) { 
        this.laboratory = value;
        notifyObservers(this.laboratory);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Test Code")
    public String getTestCode ( ) { 
        return this.testCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Test Code")
    public void setTestCode (String value) { 
        this.testCode = value;
        notifyObservers(this.testCode);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Specimen types")
    public String getSpecimenTypes ( ) { 
        return this.specimenTypes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Specimen types")
    public void setSpecimenTypes (String value) { 
        this.specimenTypes = value;
        notifyObservers(this.specimenTypes);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Container types")
    public String getContainerTypes ( ) { 
        return this.containerTypes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Container types")
    public void setContainerTypes (String value) { 
        this.containerTypes = value;
        notifyObservers(this.containerTypes);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Collection Instructions")
    public String getCollectionInstructions ( ) { 
        return this.collectionInstructions;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Collection Instructions")
    public void setCollectionInstructions (String value) { 
        this.collectionInstructions = value;
        notifyObservers(this.collectionInstructions);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Frequency")
    public String getFrequency ( ) { 
        return this.frequency;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Frequency")
    public void setFrequency (String value) { 
        this.frequency = value;
        notifyObservers(this.frequency);
    }
 
}
 