/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RequestAccessTokenRequest 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5240136570367890738L;
    private String grantType;
    private String clientId;
    private String clientSecret;
    private String scope;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("grant_type")
    public String getGrantType ( ) { 
        return this.grantType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("grant_type")
    public void setGrantType (String value) { 
        this.grantType = value;
        notifyObservers(this.grantType);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("client_id")
    public String getClientId ( ) { 
        return this.clientId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("client_id")
    public void setClientId (String value) { 
        this.clientId = value;
        notifyObservers(this.clientId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("client_secret")
    public String getClientSecret ( ) { 
        return this.clientSecret;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("client_secret")
    public void setClientSecret (String value) { 
        this.clientSecret = value;
        notifyObservers(this.clientSecret);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("scope")
    public String getScope ( ) { 
        return this.scope;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("scope")
    public void setScope (String value) { 
        this.scope = value;
        notifyObservers(this.scope);
    }
 
}
 