/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SearchLabTestsResponse 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4917875430647130108L;
    private String alternateName;
    private LabTestData labTestData;
    private String labTestId;
    private String labTestName;
    private String id;
    private double searchScore;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("alternate_name")
    public String getAlternateName ( ) { 
        return this.alternateName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("alternate_name")
    public void setAlternateName (String value) { 
        this.alternateName = value;
        notifyObservers(this.alternateName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lab_test_data")
    public LabTestData getLabTestData ( ) { 
        return this.labTestData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lab_test_data")
    public void setLabTestData (LabTestData value) { 
        this.labTestData = value;
        notifyObservers(this.labTestData);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lab_test_id")
    public String getLabTestId ( ) { 
        return this.labTestId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lab_test_id")
    public void setLabTestId (String value) { 
        this.labTestId = value;
        notifyObservers(this.labTestId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lab_test_name")
    public String getLabTestName ( ) { 
        return this.labTestName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lab_test_name")
    public void setLabTestName (String value) { 
        this.labTestName = value;
        notifyObservers(this.labTestName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
        notifyObservers(this.id);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("search_score")
    public double getSearchScore ( ) { 
        return this.searchScore;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("search_score")
    public void setSearchScore (double value) { 
        this.searchScore = value;
        notifyObservers(this.searchScore);
    }
 
}
 