/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Usage 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4875346823573316103L;
    private String term;
    private int count;
    private double percent;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("term")
    public String getTerm ( ) { 
        return this.term;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("term")
    public void setTerm (String value) { 
        this.term = value;
        notifyObservers(this.term);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("count")
    public int getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("count")
    public void setCount (int value) { 
        this.count = value;
        notifyObservers(this.count);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("percent")
    public double getPercent ( ) { 
        return this.percent;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("percent")
    public void setPercent (double value) { 
        this.percent = value;
        notifyObservers(this.percent);
    }
 
}
 