/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example;

import com.example.controllers.*;
import com.example.http.client.HttpClient;

public class HealthOSClient {
    /**
     * Singleton access to Medicines controller
     * @return	Returns the MedicinesController instance 
     */
    public MedicinesController getMedicines() {
        return MedicinesController.getInstance();
    }

    /**
     * Singleton access to LabTests controller
     * @return	Returns the LabTestsController instance 
     */
    public LabTestsController getLabTests() {
        return LabTestsController.getInstance();
    }

    /**
     * Singleton access to Generics controller
     * @return	Returns the GenericsController instance 
     */
    public GenericsController getGenerics() {
        return GenericsController.getInstance();
    }

    /**
     * Singleton access to Food controller
     * @return	Returns the FoodController instance 
     */
    public FoodController getFood() {
        return FoodController.getInstance();
    }

    /**
     * Singleton access to Exercises controller
     * @return	Returns the ExercisesController instance 
     */
    public ExercisesController getExercises() {
        return ExercisesController.getInstance();
    }

    /**
     * Singleton access to DrugInteractions controller
     * @return	Returns the DrugInteractionsController instance 
     */
    public DrugInteractionsController getDrugInteractions() {
        return DrugInteractionsController.getInstance();
    }

    /**
     * Singleton access to Diseases controller
     * @return	Returns the DiseasesController instance 
     */
    public DiseasesController getDiseases() {
        return DiseasesController.getInstance();
    }

    /**
     * Singleton access to Chat controller
     * @return	Returns the ChatController instance 
     */
    public ChatController getChat() {
        return ChatController.getInstance();
    }

    /**
     * Singleton access to Autocomplete controller
     * @return	Returns the AutocompleteController instance 
     */
    public AutocompleteController getAutocomplete() {
        return AutocompleteController.getInstance();
    }

    /**
     * Singleton access to Authentication controller
     * @return	Returns the AuthenticationController instance 
     */
    public AuthenticationController getAuthentication() {
        return AuthenticationController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public HealthOSClient() {	
	}

    /**
     * Client initialization constructor 
     */     
    public HealthOSClient(String host, String oAuthAccessToken) {
        this();
        Configuration.host = host;
        Configuration.oAuthAccessToken = oAuthAccessToken;
    }
}